version: "3.8"
services:
  ui:
    build: ./UI
    stdin_open: true
    ports:
      - "3000:3000"
    stop_signal: SIGKILL
  stt:
    build: ./STT
    stdin_open: true
    ports:
      - "4000:4000"
    stop_signal: SIGKILL
  nlu:
    build: ./NLU
    stdin_open: true
    ports:
      - "5005:5005"
    stop_signal: SIGKILL
